<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {

        $categories = [
            'Stationery & Office Supplies' => [
                ['অফসেট কাগজ A4', 'Offset Paper A4'],
                ['অফসেট কাগজ A7', 'Offset Paper A7'],
                ['বলপেন (কালো)', 'Ball Pen (Black)'],
                ['বলপেন (লাল)', 'Ball Pen (Red)'],
                ['পাইলট কলম V7', 'Pilot Pen V7'],
                ['পেন্সিল', 'Pencil'],
                ['ইরেজার', 'Eraser'],
                ['শার্পনার', 'Sharpener'],
                ['ফাইল কাভার', 'File Cover'],
                ['ফাইল বোর্ড', 'File Board'],
                ['ফাইল ট্যাগ', 'File Tag'],
                ['রেজিস্টার খাতা নম্বর ৪', 'Register Book No. 4'],
                ['রেজিস্টার খাতা নম্বর ৬', 'Register Book No. 6'],
                ['রেজিস্টার খাতা নম্বর ১০', 'Register Book No. 10'],
                ['রেজিস্টার খাতা নম্বর ১২', 'Register Book No. 12'],
                ['স্ট্যাপলার (ছোট)', 'Stapler (Small)'],
                ['স্ট্যাপলার (বড়)', 'Stapler (Large)'],
                ['পিন রিমুভার', 'Pin Remover'],
                ['পাঞ্চ মেশিন (সিঙ্গেল)', 'Punch Machine (Single)'],
                ['পাঞ্চ মেশিন (ডাবল)', 'Punch Machine (Double)'],
                ['স্ট্যাপলার পিন (বড়)', 'Stapler Pins (Large)'],
                ['স্ট্যাপলার পিন (ছোট)', 'Stapler Pins (Small)'],
                ['পেপার ওয়েট', 'Paper Weight'],
                ['পেন পট', 'Pen Holder'],
                ['জেমস ক্লিপ', 'Gem Clip'],
                ['বাইন্ডার ক্লিপ (ছোট)', 'Binder Clip (Small)'],
                ['বাইন্ডার ক্লিপ (মাঝারি)', 'Binder Clip (Medium)'],
                ['বাইন্ডার ক্লিপ (বড়)', 'Binder Clip (Large)'],
                ['গাম টিউব', 'Gum Tube'],
                ['আইকা', 'Glue Adhesive (Aica)'],
                ['Glue Stick', 'Glue Stick'],
                ['ক্যালকুলেটর', 'Calculator'],
                ['স্কেল (স্টিল)', 'Steel Scale'],
                ['স্কেল (কাঠ)', 'Wooden Scale'],
                ['কাঁচি (বড়)', 'Scissors (Large)'],
                ['কাঁচি (মাঝারি)', 'Scissors (Medium)'],
                ['চাকু (মাঝারি)', 'Cutter Knife (Medium)'],
                ['কসটেপ (ছোট)', 'Scotch Tape (Small)'],
                ['কসটেপ (মাঝারি)', 'Scotch Tape (Medium)'],
                ['কসটেপ (বড়)', 'Scotch Tape (Large)'],
                ['বান্ডিং টেপ', 'Binding Tape'],
                ['মাস্কিং টেপ', 'Masking Tape'],
                ['ম্যানেজমেন্ট পাঞ্চ ফাইল', 'Management Punch File'],
                ['সেমিনার ক্লিপ ফাইল', 'Seminar Clip File'],
                ['রিং ফাইল', 'Ring File'],
                ['ইনভেলাপ খাম (সাদা) ১০×৪ ইঞ্চি', 'White Envelope 10×4 Inch'],
                ['ইনভেলাপ খাম (সাদা) NU লোগোসহ ১০×৪ ইঞ্চি', 'White Envelope with NU Logo 10×4 Inch'],
                ['খাকি ইনভেলাপ খাম NU লোগোসহ', 'Khaki Envelope with NU Logo'],
                ['খাকি খাম A4 (সনদ সাইজ)', 'Khaki Envelope A4 (Certificate Size)'],
                ['খাকি খাম Legal', 'Khaki Envelope Legal Size'],
                ['খাকি খাম সুতা জড়ানো A4', 'Khaki Envelope with String A4'],
                ['খাকি খাম সুতা জড়ানো Legal', 'Khaki Envelope with String Legal Size'],
                ['স্ট্যাম্প প্যাড', 'Stamp Pad'],
                ['স্ট্যাম্প প্যাডের কালি', 'Stamp Pad Ink'],
                ['সাদা সুতার গুটি', 'White Thread Roll'],
                ['লাল সুতার গুটি', 'Red Thread Roll'],
                ['하이লাইটার পেন', 'Highlighter Pen'],
                ['ফোড়ন', 'Push Pin'],
                ['তালা (মাঝারি)', 'Padlock (Medium)'],
                ['তালা (বড়)', 'Padlock (Large)'],
                ['পেন্সিল ব্যাটারি', 'AA Battery'],
                ['রিমোট ব্যাটারি', 'Remote Battery'],
                ['মাইক্রোফোন ব্যাটারি', 'Microphone Battery'],
                ['হোয়াইট বোর্ড মার্কার', 'Whiteboard Marker'],
                ['পারমানেন্ট মার্কার', 'Permanent Marker'],
                ['কালার সাইন পেন', 'Color Sign Pen'],
                ['পোস্টার পেপার', 'Poster Paper'],
                ['আর্ট পেপার', 'Art Paper'],
                ['রঙিন পেপার', 'Colored Paper'],
                ['আইডি কার্ডের কাভার', 'ID Card Cover'],
                ['আইডি কার্ডের ফিতা', 'ID Card Ribbon'],
                ['আইডি কার্ডের ট্যাগ', 'ID Card Tag'],
                ['টেবিল ঝুড়ি', 'Table Basket'],
                ['বালতি (মাঝারি)', 'Bucket (Medium)'],
                ['মগ', 'Mug'],
                ['প্লাস্টিক মোড়া', 'Plastic Wrap'],
                ['বদনা', 'Water Pot'],
            ],
            'Electronics & IT Items' => [
                ['Desktop কম্পিউটার', 'Desktop Computer'],
                ['Laptop কম্পিউটার', 'Laptop Computer'],
                ['লেজার প্রিন্টার', 'Laser Printer'],
                ['লেজার প্রিন্টার (কালার)', 'Color Laser Printer'],
                ['ফটোকপিয়ার মেশিন Sharp-NU', 'Sharp Photocopier Machine (NU)'],
                ['ফটোকপিয়ার মেশিন Canon-CEDP', 'Canon Photocopier Machine (CEDP)'],
                ['ফটোকপিয়ার মেশিন', 'Photocopier Machine'],
                ['UPS', 'UPS'],
                ['মাউস', 'Mouse'],
                ['মাউস প্যাড', 'Mouse Pad'],
                ['কি-বোর্ড', 'Keyboard'],
                ['হেডফোন', 'Headphone'],
                ['ওয়েব ক্যামেরা', 'Webcam'],
                ['ল্যাপটপ সিকিউরিটি ক্যাবল', 'Laptop Security Cable'],
                ['স্পিকার', 'Speaker'],
                ['Laser Pointer', 'Laser Pointer'],
                ['লেজার প্রিন্টার টোনার 76A (Black)', 'Laser Printer Toner 76A (Black)'],
                ['লেজার প্রিন্টার টোনার 26A (Black)', 'Laser Printer Toner 26A (Black)'],
                ['লেজার প্রিন্টার টোনার (color)', 'Laser Printer Toner (Color)'],
                ['ফটোকপিয়ার টোনার NPG-73', 'Photocopier Toner NPG-73'],
                ['ফটোকপিয়ার টোনার Sharp MX-315AT', 'Photocopier Toner Sharp MX-315AT'],
                ['ফটোকপিয়ার টোনার', 'Photocopier Toner'],
                ['ওয়াইফাই রাউটার', 'WiFi Router'],
                ['মাল্টিপ্লাগ', 'Multi Plug'],
                ['Network Switch Cisco 24-port', 'Cisco 24-Port Network Switch'],
                ['TP-Link Switch', 'TP-Link Switch'],
                ['হার্ড ডিস্ক ৫০০ জিবি', 'Hard Disk 500 GB'],
                ['হার্ড ডিস্ক ১ টেরা', 'Hard Disk 1 TB'],
                ['হার্ড ডিস্ক ২ টেরা', 'Hard Disk 2 TB'],
                ['এসএসডি ৫০০ জিবি', 'SSD 500 GB'],
                ['এসএসডি ১ টেরা', 'SSD 1 TB'],
                ['এসএসডি ২ টেরা', 'SSD 2 TB'],
                ['পেন ড্রাইভ ৮ জিবি', 'Pen Drive 8 GB'],
                ['পেন ড্রাইভ ১৬ জিবি', 'Pen Drive 16 GB'],
                ['উইন্ডোজ Disk', 'Windows Disk'],
                ['অ্যান্টিভাইরাস', 'Antivirus'],
                ['জুম লাইসেন্স', 'Zoom License'],
                ['Projector with Screen', 'Projector with Screen'],
                ['Samsung Galaxy Tab', 'Samsung Galaxy Tab'],
                ['Lenovo Tab', 'Lenovo Tab'],
                ['Tab accessories', 'Tab Accessories'],
                ['ইউপিএস ডাবল ব্যাটারি', 'UPS Double Battery'],
                ['ইউপিএস সিঙ্গেল ব্যাটারি', 'UPS Single Battery'],
                ['ভিজিএ ক্যাবল', 'VGA Cable'],
                ['ইউএসবি টু ভিজিএ কনভার্টার', 'USB to VGA Converter'],
                ['ইউএসবি ডাটা ক্যাবল', 'USB Data Cable'],
                ['Air Blower', 'Air Blower'],
            ],
            'Cleaning & Toiletries Items' => [
                ['ফেসিয়াল টিস্যু', 'Facial Tissue'],
                ['হ্যান্ডওয়াশ ২৫০ গ্রাম', 'Hand Wash 250 gm'],
                ['লাক্স সাবান ১০০ গ্রাম', 'Lux Soap 100 gm'],
                ['হুইল সাবান', 'Wheel Soap'],
                ['ডিটারজেন্ট পাউডার ৫০০ গ্রাম', 'Detergent Powder 500 gm'],
                ['ভিম লিকুইড ২৫০ গ্রাম', 'Vim Liquid 250 gm'],
                ['স্যাভলন লিকুইড', 'Savlon Liquid'],
                ['মিস্টার ব্রাশো গ্লাস ক্লিনার', 'Mr. Brasso Glass Cleaner'],
                ['ডাস্টার কাপড়', 'Duster Cloth'],
                ['ফুল ঝাড়ু', 'Full Broom'],
                ['শলার ঝাড়ু', 'Stick Broom'],
                ['পাটের মপ', 'Jute Mop'],
                ['ফিনাইল ৩ লিটার', 'Phenyl 3 Liter'],
                ['ন্যাপথলিন', 'Naphthalene'],
                ['হারপিক ৭৫০ গ্রাম', 'Harpic 750 gm'],
                ['ব্লিচিং পাউডার ৫০০ গ্রাম', 'Bleaching Powder 500 gm'],
                ['টয়লেট টিস্যু', 'Toilet Tissue'],
                ['টয়লেট ব্রাশ (গোলাকার)', 'Toilet Brush (Round)'],
                ['ভিক্সল ৫০০ গ্রাম', 'Vixol 500 gm'],
                ['অ্যারোসল', 'Aerosol Spray'],
                ['এয়ার ফ্রেশনার', 'Air Freshener'],
            ],
            'Crockery & Kitchen Items' => [
                ['সিরামিক প্লেট', 'Ceramic Plate'],
                ['সিরামিক হাফ প্লেট', 'Ceramic Half Plate'],
                ['সিরামিক রাইস ডিস', 'Ceramic Rice Dish'],
                ['সিরামিক কারি বোল', 'Ceramic Curry Bowl'],
                ['সিরামিক ছোট বাটি', 'Small Ceramic Bowl'],
                ['সিরামিক কাপ-পিরিচ (VIP)', 'Ceramic Cup & Saucer (VIP)'],
                ['সিরামিক কাপ-পিরিচ (সাধারণ)', 'Ceramic Cup & Saucer (Regular)'],
                ['সিরামিক টি-пот', 'Ceramic Tea Pot'],
                ['সিরামিক সুগার পট', 'Ceramic Sugar Pot'],
                ['চা চামচ', 'Tea Spoon'],
                ['কাঁটা চামচ', 'Fork'],
                ['কাঁটা চামচ (VIP)', 'Fork (VIP)'],
                ['টেবিল চামচ', 'Table Spoon'],
                ['ডালের চামচ', 'Dal Spoon'],
                ['কারী চামচ', 'Curry Spoon'],
                ['ভাতের চামচ', 'Rice Spoon'],
                ['কাঁচের গ্লাস', 'Glass Tumbler'],
                ['প্লাস্টিক জগ', 'Plastic Jug'],
                ['কাঁচের জগ', 'Glass Jug'],
                ['ষ্টিল ট্রে', 'Steel Tray'],
                ['কাঠের ট্রে', 'Wooden Tray'],
                ['সিলভারের বোল', 'Silver Bowl'],
                ['ষ্টিলের বোল (বড়)', 'Steel Bowl (Large)'],
                ['ষ্টিলের বোল (মাঝারি)', 'Steel Bowl (Medium)'],
                ['সিলভারের কেতলি', 'Silver Kettle'],
                ['ডাবল বার্নার চুলা', 'Double Burner Stove'],
                ['কড়াই (ঢাকনাসহ)', 'Wok with Lid'],
                ['টিফিন ক্যারিয়ার', 'Tiffin Carrier'],
                ['ওয়াশিংপট', 'Washing Pot'],
                ['ভাতের হাড়ি', 'Rice Pot'],
                ['কড়াই', 'Wok'],
                ['কড়াই ঢাকনা', 'Wok Lid'],
                ['সসপেন ঢাকনাসহ', 'Saucepan with Lid'],
                ['ব্লেন্ডার মেশিন', 'Blender Machine'],
                ['সবজি কাটার (স্লাইসার)', 'Vegetable Cutter (Slicer)'],
                ['চপিং বোর্ড (বড়)', 'Chopping Board (Large)'],
                ['চিলমচি', 'Wash Basin Bowl'],
            ],
        ];

        foreach ($categories as $catName => $products) {
            $category = Category::create(['name' => $catName]);

            foreach ($products as $product) {
                Product::create([
                    'category_id' => $category->id,
                    'name_bn' => $product[0],
                    'name_en' => $product[1],
                    'stock' => 100, // Default Initial Stock
                ]);
            }
        }
    }
}
